SRV_NAME    = "SLIRCd"
SRV_VERSION = "0.1"
SRV_WELCOME = "Welcome to %s v%s, the ugliest IRC server in the world." % (SRV_NAME, SRV_VERSION)

RPL_WELCOME				= '001'
RPL_YOURHOST			= '002'
RPL_CREATED				= '003'
RPL_MYINFO				= '004'
RPL_BOUNCE				= '005'

RPL_NAMREPLY			= '353'
RPL_ENDOFNAMES			= '354'

RPL_MOTDSTART			= '375'
RPL_ENDOFMOTD			= '376'


ERR_NOSUCHNICK			= '401'
ERR_NOSUCHCHANNEL		= '403'
ERR_CANNOTSENDTOCHAN	= '404'
ERR_UNKNOWNCOMMAND		= '421'
ERR_ERRONEUSNICKNAME	= '432'
ERR_NICKNAMEINUSE		= '433'
ERR_NEEDMOREPARAMS		= '461'